#!/usr/bin/env python3
"""Regenerate src/apps_local/insider/InsiderWords.h from tools_local/insider/insider_words.txt.

    ./tools_local/insider/gen_insider_words.py

The output is committed, the same as the icon headers: a checkout should build
without running any generator. Edit the .txt, run this, run
./bin/clang-format-fix, and commit both -- clang-format packs the one-word-per-
line table this emits, so skipping it means the next person's format run shows
five hundred lines of diff over an identical word list.

The deck ships in flash rather than on the SD card. It is about 6KB, the card is
not guaranteed to hold anything, and a party game that cannot deal a word
because a file is missing has no fallback worth writing.
"""

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE = REPO / "tools_local" / "insider_words.txt"
OUT = REPO / "src" / "apps_local" / "insider" / "InsiderWords.h"

# The tile face is drawn at a fixed cut and the reveal card is sized to the
# longest word, so a word that outgrows this changes a layout rather than just a
# buffer. Fail loudly instead of silently clipping one word in five hundred.
MAX_LEN = 15


def main() -> int:
    words = []
    for line in SOURCE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        words.append(line)

    if len(words) != len(set(words)):
        dupes = sorted({w for w in words if words.count(w) > 1})
        print(f"duplicate words: {dupes}", file=sys.stderr)
        return 1
    for word in words:
        if not re.fullmatch(r"[A-Z]+", word):
            print(f"not plain uppercase ASCII: {word!r}", file=sys.stderr)
            return 1
        if len(word) > MAX_LEN:
            print(f"longer than {MAX_LEN}: {word!r}", file=sys.stderr)
            return 1

    longest = max(words, key=len)
    lines = [
        "#pragma once",
        "",
        "// Generated by tools_local/insider/gen_insider_words.py from tools_local/insider/insider_words.txt.",
        "// Do not edit.",
        "",
        "#include <cstdint>",
        "",
        "namespace insider {",
        "",
        f"// {len(words)} words. Longest is {longest!r} at {len(longest)} characters, which is what",
        "// the reveal card is sized against.",
        f"inline constexpr int kWordCount = {len(words)};",
        f"inline constexpr int kMaxWordLen = {len(longest)};",
        "",
        "// constexpr, so the table and every string in it land in flash rather than",
        "// being copied into the 380KB of DRAM at startup.",
        "inline constexpr const char* kWords[kWordCount] = {",
    ]
    for word in words:
        lines.append(f'    "{word}",')
    lines += ["};", "", "}  // namespace insider", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)} ({len(words)} words)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
