#!/usr/bin/env python3
"""Emit the avatar parts and word lists for the website, from the device's own.

The site draws a live face-and-name generator. It has to be the *same* data the
firmware uses or it is a mockup, which docs/identity.md rules out: ornament has
to be made of the app's own material. So the word lists are read out of
PlayerName.cpp and the art out of assets_local/avatar/, and this script is the
only thing standing between them and the page.

    python tools_local/avatar/gen_avatar_web.py

Writes site/assets/avatar-data.js. Re-run it when a part or a word changes; the
assert on 14-apiece will fail loudly if the two ever drift.
"""

import io
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
ART = REPO / "assets_local" / "avatar"
NAMES = REPO / "src" / "apps_local" / "player" / "PlayerName.cpp"
OUT = REPO / "site" / "assets" / "avatar-data.js"


def word_list(src, symbol):
    """Pull `constexpr const char* kX[] = {...}` out of the C++ verbatim."""
    m = re.search(
        r"constexpr const char\* " + symbol + r"\[\]\s*=\s*\{(.*?)\};", src, re.DOTALL
    )
    if not m:
        sys.exit(f"{symbol} not found in PlayerName.cpp")
    words = re.findall(r'"([A-Z]+)"', m.group(1))
    assert len(words) == 14, f"{symbol}: expected 14 words, got {len(words)}"
    return words


WRAPPER = (
    'fill="none" stroke="black" stroke-width="5" '
    'stroke-linecap="round" stroke-linejoin="round"'
)


def check_wrapper(path, text):
    """Every part must share one set of presentation attributes.

    They live on each file's <svg>, which this script strips, so the page
    supplies them once instead. A part that carried different ones would render
    wrong there and nowhere else -- which is how the first version filled the
    hair solid over the eyes.
    """
    head = text[: text.index(">")]
    for attr in WRAPPER.split('" '):
        key = attr.split("=")[0]
        if key not in head:
            sys.exit(f"{path.name}: missing {key} on <svg>; the page assumes {WRAPPER}")


def inner_svg(path):
    """The drawing commands, without the <svg> wrapper.

    Every part is authored on one shared 120x120 viewBox precisely so the layers
    stay in register with no per-part offsets, so the wrapper is the same for
    all of them and belongs in the page rather than repeated 44 times here.
    """
    s = io.open(path, encoding="utf-8").read()
    check_wrapper(path, s)
    body = re.sub(r"^.*?<svg[^>]*>", "", s, flags=re.DOTALL)
    body = re.sub(r"</svg>\s*$", "", body, flags=re.DOTALL)
    return re.sub(r"\s+", " ", body).strip()


def main():
    src = io.open(NAMES, encoding="utf-8").read()
    lists = {
        "hair": word_list(src, "kHair"),
        "eyes": word_list(src, "kEyes"),
        "mouth": word_list(src, "kMouth"),
    }

    parts = {}
    missing = []
    for slot, words in lists.items():
        parts[slot] = {}
        for w in words:
            p = ART / f"{slot}_{w}.svg"
            if not p.exists():
                missing.append(p.name)
                continue
            parts[slot][w] = inner_svg(p)
    if missing:
        sys.exit("missing art: " + ", ".join(missing))

    base = ART / "base.svg"
    if not base.exists():
        sys.exit("missing assets_local/avatar/base.svg")

    payload = {"words": lists, "base": inner_svg(base), "parts": parts}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    io.open(OUT, "w", encoding="utf-8").write(
        "// Generated by tools_local/avatar/gen_avatar_web.py -- do not edit.\n"
        "// The device's own word lists and avatar art, so the face the page\n"
        "// draws for a name is the face the device draws for it.\n"
        "window.CROSSPLAY_AVATAR = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(REPO)} ({kb:.1f} KB, {14**3} faces)")


if __name__ == "__main__":
    main()
