#!/bin/bash
# Regenerate src/apps_local/player/PlayerAvatarArt.h from assets_local/avatar/.
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/avatar/gen_avatar.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the SVGs, run this, commit both.
#
# This is the SDK's own icon generator, pointed at our SVGs instead of Lucide's.
# Worth saying why, because writing a second one was the obvious mistake: it
# already rasterises a whole canvas at a requested size and packs it 1-bpp, and
# a whole canvas is exactly what keeps the layers in register. Solitaire's pips
# were hand-rasterised three times before somebody noticed this script existed.
#
# Two sizes, and the small one is not free. 120px is the settings screen, where
# the face is the subject. 48px is everywhere the avatar sits next to a name in
# a row -- the shelf footer and both link seats. There is no third size: pick
# whichever of these two a new place is closer to.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/avatar/avatar.txt \
  --svgdir assets_local/avatar \
  --sizes 48,120 \
  --out src/apps_local/player/PlayerAvatarArt.h

# The generator hardcodes "from Lucide SVGs" in its banner, which is a lie in
# this one file and exactly the kind of stale provenance somebody acts on later.
# Asserted rather than sed'd blind: if the SDK reworks its banner, this stops
# the build instead of silently leaving the wrong sentence behind.
OUT=src/apps_local/player/PlayerAvatarArt.h
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/avatar/gen_avatar.sh from assets_local/avatar/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_avatar.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 1
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

# The generator emits one array per line and clang-format rewraps them, so
# without this a regeneration shows thousands of lines of diff over
# byte-identical data and hides whatever actually changed.
./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i "$OUT"
echo "wrote $OUT"
