#!/bin/bash
# Regenerate src/apps_local/seasalt/SeaSaltArt.h (Lucide card marks) and
# src/apps_local/seasalt/SeaSaltMarks.h (our filled colour marks).
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/seasalt/gen_seasalt_art.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the manifests or SVGs, run this, commit both.
#
# Two passes, like Jaipur's: the card marks are Lucide's, the filled colour
# marks are ours, and two headers keeps that boundary visible.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"

# 48 for a hand card, 40 for the four-row hand and the pile tops, 24 for the
# how-to's inline mentions.
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/seasalt/seasalt_cards.txt \
  --svgdir freeink-sdk/libs/assets/Icons/lucide/icons \
  --sizes 24,40,48 \
  --out src/apps_local/seasalt/SeaSaltArt.h
echo "wrote src/apps_local/seasalt/SeaSaltArt.h"

# The filled colour marks are ours. One cut: 24 reads on both card sizes.
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/seasalt/seasalt_marks.txt \
  --svgdir assets_local/seasalt \
  --sizes 24 \
  --out src/apps_local/seasalt/SeaSaltMarks.h

OUT=src/apps_local/seasalt/SeaSaltMarks.h
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/seasalt/gen_seasalt_art.sh from assets_local/seasalt/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_seasalt_art.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 1
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i src/apps_local/seasalt/SeaSaltArt.h "$OUT"
echo "wrote $OUT"
