#!/bin/bash
# Every Sea Salt screen on one sheet, driven through the simulator.
#
#   ./tools_local/seasalt/seasalt_sheet.sh
#
# Writes qa-artifacts/seasalt_sheet.png. Run it after any screen change and
# LOOK at it: the tabs-in-the-wrong-font, the morphing card shapes and the
# floating keep cards all shipped because each screen was only ever checked
# alone, right after being written. A sheet makes the drift between screens
# the thing you see first.
#
# This script is also the answer to "how did you capture that": every shot's
# recipe is a tap script below, not a memory.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"

# A deterministic mid-game save (round 2, 12-7, eight cards, five kinds, both
# piles live), so the board screens show a real position rather than an empty
# opening. Generated by the same core the firmware runs.
c++ -std=c++17 -O2 -Isrc/apps_local/seasalt src/apps_local/seasalt/SeaSaltCore.cpp \
  tools_local/seasalt/seasalt_mkstate.cpp -o /tmp/seasalt_mkstate
mkdir -p fs_agent/.crosspoint

OUT=qa-artifacts
IN='2000:TAP:120,635;3600:TAP:240,605'   # Games -> SEA SALT

# A Play-step save with 7+ points: board, selection, the call chooser.
/tmp/seasalt_mkstate call > fs_agent/.crosspoint/seasalt.sav
./scripts_local/sim-shot.sh \
  "$IN;5600:TAP:240,535;7600:TAP:69,378;9600:TAP:408,770;12000:QUIT" \
  "5000:$OUT/sheet_menu.bmp;7200:$OUT/sheet_board.bmp;9200:$OUT/sheet_selected.bmp;11400:$OUT/sheet_call.bmp"

# A Take-step save: the draw flow, all of it ON the board -- deck deals two
# into the grid, tap cell 0 to keep it, then the pile row takes the other.
/tmp/seasalt_mkstate take > fs_agent/.crosspoint/seasalt.sav
./scripts_local/sim-shot.sh \
  "$IN;5600:TAP:240,535;7600:TAP:88,220;9600:TAP:69,378;12000:QUIT" \
  "9200:$OUT/sheet_keep.bmp;11400:$OUT/sheet_pile.bmp"

# every tutorial page: each tap advances one page
./scripts_local/sim-shot.sh \
  "$IN;5600:TAP:240,733;7400:TAP:240,400;9200:TAP:240,400;11000:TAP:240,400;12800:TAP:240,400;14600:TAP:240,400;17000:QUIT" \
  "7000:$OUT/sheet_howto1.bmp;8800:$OUT/sheet_howto2.bmp;10600:$OUT/sheet_howto3.bmp;12400:$OUT/sheet_howto4.bmp;14200:$OUT/sheet_howto5.bmp;16000:$OUT/sheet_howto6.bmp"

uv run --quiet --with pillow python - <<'PY'
from PIL import Image, ImageDraw
names = ["menu", "board", "selected", "keep", "pile", "call", "howto1", "howto2", "howto3", "howto4", "howto5", "howto6"]
ims = []
for n in names:
    try:
        ims.append((n, Image.open(f"qa-artifacts/sheet_{n}.png").convert("L")))
    except FileNotFoundError:
        print(f"  missing sheet_{n}.png -- its tap script needs updating")
cols = 4
w, h = ims[0][1].size
sheet = Image.new("L", (cols * (w + 16) + 16, ((len(ims) + cols - 1) // cols) * (h + 56) + 16), 230)
d = ImageDraw.Draw(sheet)
for i, (n, im) in enumerate(ims):
    x = 16 + (i % cols) * (w + 16)
    y = 16 + (i // cols) * (h + 56)
    d.text((x + 4, y + 2), n.upper(), fill=0)
    sheet.paste(im, (x, y + 40))
sheet.save("qa-artifacts/seasalt_sheet.png")
print("wrote qa-artifacts/seasalt_sheet.png")
PY
