#!/bin/bash
# Regenerate src/apps_local/jaipur/JaipurArt.h from assets_local/jaipur/.
#
#   brew install librsvg          # rsvg-convert, the only external dependency
#   ./tools_local/jaipur/gen_jaipur_art.sh
#
# The output is committed, because regenerating needs librsvg and a checkout
# should build without it. Edit the SVGs, run this, commit both.
#
# The SDK's own icon generator, pointed at our SVG instead of Lucide's, the same
# way tools_local/avatar/gen_avatar.sh does. One cut per row of the board, because each
# row leaves the mark a different amount of room: 56 for a market card, which
# carries nothing but the mark; 44 for a hand card, under its count; 32 for a
# pile card, which has a price above the mark and the depth pips below it.
set -euo pipefail
REPO="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../.." && pwd)"
cd "$REPO"
# Two passes, because gen_icons.py takes one --svgdir and these have different
# provenance: the goods are Lucide's, the camel is ours. Two headers keeps that
# boundary visible rather than blending licensed art into hand-drawn.
uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/jaipur/jaipur_goods.txt \
  --svgdir freeink-sdk/libs/assets/Icons/lucide/icons \
  --sizes 32,44,56 \
  --out src/apps_local/jaipur/JaipurGoods.h
echo "wrote src/apps_local/jaipur/JaipurGoods.h"

uv run --quiet --with pillow python freeink-sdk/libs/assets/Icons/tools/gen_icons.py \
  --manifest tools_local/jaipur/jaipur_art.txt \
  --svgdir assets_local/jaipur \
  --sizes 32,44,56 \
  --out src/apps_local/jaipur/JaipurArt.h

# The generator hardcodes "from Lucide SVGs" in its banner, which is a lie in
# this file. Asserted rather than sed'd blind: if the SDK reworks its banner
# this stops the build instead of leaving the wrong provenance behind.
OUT=src/apps_local/jaipur/JaipurArt.h
WRONG="// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit."
RIGHT="// Generated by tools_local/jaipur/gen_jaipur_art.sh from assets_local/jaipur/*.svg. Do not edit."
grep -qF "$WRONG" "$OUT" || { echo "gen_icons.py banner changed; update gen_jaipur_art.sh" >&2; exit 1; }
uv run --quiet python -c "
import sys
path, wrong, right = sys.argv[1:4]
text = open(path).read()
assert text.count(wrong) == 1
open(path, 'w').write(text.replace(wrong, right))
" "$OUT" "$WRONG" "$RIGHT"

./bin/clang-format-fix >/dev/null 2>&1 || clang-format -i "$OUT"
echo "wrote $OUT"
