#!/usr/bin/env python3
"""Generate the FSRS regression vectors from a real Anki collection.

The point of this file is that host-tests/study does not assert against
hand-written numbers or against a second implementation of the same formulas.
It asserts that StudyFsrs reproduces the memory state Anki itself computed and
stored, for every card in Mario's collection that has one.

    tools_local/study/gen_fsrs_vectors.py \
        ~/Library/Application\\ Support/Anki2/User\\ 1/collection.anki2 \
        host-tests/study/FsrsVectors.h

Re-run it after studying if you want fresher vectors; the committed header is
a snapshot and does not need to track the collection.
"""

import argparse
import json
import pathlib
import sqlite3
import sys

# Revlog `type` 3 is a filtered-deck ("cram") review. Anki does not feed those
# into FSRS when rebuilding memory state, because rescheduling is off in those
# decks. Including them costs 42 of 301 cards, so the exclusion is load-bearing
# and not a tidy-up. See the note at the top of StudyFsrs.h.
REVLOG_FILTERED = 3


def open_collection(path):
    db = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    # Anki installs a custom collation; without it any query touching a name
    # column fails with "no such collation sequence: unicase".
    db.create_collation(
        "unicase", lambda a, b: (a.lower() > b.lower()) - (a.lower() < b.lower())
    )
    return db


def collect(db, deck_like):
    crt = db.execute("select crt from col").fetchone()[0]
    day = lambda ms: (ms // 1000 - crt) // 86400  # noqa: E731

    rows = db.execute(
        """select c.id, c.data from cards c join decks d on d.id = c.did
           where c.data like '%"s":%' and d.name like ?""",
        (deck_like,),
    ).fetchall()

    out = []
    for cid, data in rows:
        state = json.loads(data)
        if "s" not in state or "d" not in state:
            continue
        revs = db.execute(
            "select id, ease, type from revlog where cid = ? order by id", (cid,)
        ).fetchall()

        steps, prev_day = [], None
        for ms, ease, kind in revs:
            if not 1 <= ease <= 4 or kind == REVLOG_FILTERED:
                continue
            d = day(ms)
            steps.append((0 if prev_day is None else d - prev_day, ease))
            prev_day = d
        if steps:
            out.append((cid, steps, state["s"], state["d"]))
    return out


def emit(cards, dest):
    lines = [
        "#pragma once",
        "",
        "// GENERATED by tools_local/study/gen_fsrs_vectors.py -- do not edit.",
        "//",
        "// Every entry is one real card out of Mario's Anki collection: the whole",
        "// sequence of (days since previous review, button pressed) that the card",
        "// actually received, and the stability/difficulty Anki stored as a result.",
        "",
        "#include <cstdint>",
        "",
        "namespace study::vectors {",
        "",
        "struct Step {",
        "  int16_t elapsedDays;",
        "  uint8_t rating;",
        "};",
        "",
        "struct Card {",
        "  int64_t id;",
        "  const Step* steps;",
        "  int stepCount;",
        "  float expectedStability;",
        "  float expectedDifficulty;",
        "};",
        "",
    ]
    for cid, steps, _s, _d in cards:
        body = ", ".join(f"{{{e}, {r}}}" for e, r in steps)
        lines.append(f"inline constexpr Step kSteps{cid}[] = {{{body}}};")
    lines += ["", "inline constexpr Card kCards[] = {"]
    for cid, steps, s, d in cards:
        lines.append(f"    {{{cid}LL, kSteps{cid}, {len(steps)}, {s:.6f}f, {d:.6f}f}},")
    lines += [
        "};",
        "",
        f"inline constexpr int kCardCount = {len(cards)};",
        "",
        "}  // namespace study::vectors",
        "",
    ]
    dest.write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("collection", type=pathlib.Path)
    ap.add_argument("output", type=pathlib.Path)
    ap.add_argument(
        "--deck", default="Mandarin%", help="SQL LIKE pattern for the deck name"
    )
    args = ap.parse_args()

    if not args.collection.exists():
        sys.exit(f"no collection at {args.collection}")
    cards = collect(open_collection(args.collection), args.deck)
    if not cards:
        sys.exit(
            "no cards with FSRS memory state matched -- is FSRS enabled, and is --deck right?"
        )
    emit(cards, args.output)
    print(
        f"wrote {len(cards)} vectors ({sum(len(s) for _, s, _, _ in cards)} reviews) to {args.output}"
    )


if __name__ == "__main__":
    main()
