"""Re-emit generated icons rotated counter-clockwise, for GfxRenderer::drawIcon.

Usage: rotate_icons.py <in.h> <out.h> <alias> [<alias> ...]

See the note in gen_toybox_icons.sh: the old drawIcon path rotates its input by
-90, so bitmaps meant for it are stored rotated the other way. Everything in
apps_local uses the modern path and wants the upright originals, so this writes
a second copy rather than changing the first.
"""
import re
import sys


def read_bits(src, alias):
    m = re.search(r"icon_" + alias + r"_32_bits\[\] = \{([^}]+)\};", src)
    if m is None:
        raise SystemExit("no such icon: " + alias)
    return [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(1))]


def rotate90(bits, size=32):
    def get(x, y):
        return (bits[y * (size // 8) + x // 8] >> (7 - x % 8)) & 1

    out = bytearray(size * (size // 8))
    for y in range(size):
        for x in range(size):
            # Counter-clockwise. Verified by rotating a freshly generated
            # `folder` and comparing it against upstream's own stored
            # FolderIcon: ccw matches its orientation, cw does not. (They are
            # not byte-equal -- the Lucide source has moved since upstream
            # generated theirs -- so the check is the shape, not the bytes.)
            if get(size - 1 - y, x):
                out[y * (size // 8) + x // 8] |= 1 << (7 - x % 8)
    return out


def main():
    src = open(sys.argv[1]).read()
    lines = ["#pragma once", "#include <cstdint>", "",
             "// Generated by tools_local/toybox/rotate_icons.py. Do not edit.",
             "// Pre-rotated for GfxRenderer::drawIcon; see gen_toybox_icons.sh.", ""]
    for alias in sys.argv[3:]:
        rows = rotate90(read_bits(src, alias))
        body = ", ".join("0x%02X" % b for b in rows)
        lines += ["// size: 32x32", "static const uint8_t Shelf%sIcon[] = {%s};" % (alias.capitalize(), body), ""]
    open(sys.argv[2], "w").write("\n".join(lines))


main()
