#!/usr/bin/env python3
"""Generate the compact Kanto species table from the pinned offline CSV."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path


REVISION = "837b3642001d4853249114d2b5601d46e1004a45"
PROVENANCE = f"# PokeAPI api-data revision {REVISION}"
HEADERS = (
    "id",
    "name",
    "primary_type",
    "secondary_type",
    "gender_rate",
    "capture_rate",
    "stage",
    "acquisition",
    "evolutions",
)
TYPES = {
    "None",
    "Normal",
    "Fire",
    "Water",
    "Electric",
    "Grass",
    "Ice",
    "Fighting",
    "Poison",
    "Ground",
    "Flying",
    "Psychic",
    "Bug",
    "Rock",
    "Ghost",
    "Dragon",
    "Dark",
    "Steel",
    "Fairy",
}
STAGES = {"Base", "Middle", "Final"}
ACQUISITIONS = {"Wild", "EvolutionOnly", "Legendary", "Special"}
ITEMS = {"None", "MoonStone", "FireStone", "ThunderStone", "WaterStone", "LeafStone", "LinkCable"}


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class Evolution:
    target: int
    trigger: str
    level: int
    item: str


@dataclass(frozen=True)
class Species:
    species_id: int
    name: str
    primary_type: str
    secondary_type: str
    gender_rate: int
    capture_rate: int
    stage: str
    acquisition: str
    evolutions: tuple[Evolution, ...]


def parse_evolutions(value: str, species_id: int) -> tuple[Evolution, ...]:
    if not value:
        return ()
    output: list[Evolution] = []
    for encoded in value.split(";"):
        fields = encoded.split(":")
        if len(fields) != 4:
            raise DataError(f"species {species_id}: invalid evolution {encoded!r}")
        target_text, trigger, level_text, item = fields
        try:
            target = int(target_text)
            level = int(level_text)
        except ValueError as error:
            raise DataError(f"species {species_id}: non-numeric evolution") from error
        if not 1 <= target <= 151 or trigger not in {"Level", "Item"} or item not in ITEMS:
            raise DataError(f"species {species_id}: invalid evolution values")
        if (trigger == "Level" and (not 1 <= level <= 100 or item != "None")) or (
            trigger == "Item" and (level != 0 or item == "None")
        ):
            raise DataError(f"species {species_id}: inconsistent evolution trigger")
        output.append(Evolution(target, trigger, level, item))
    if len(output) > 3:
        raise DataError(f"species {species_id}: more than three Kanto evolutions")
    return tuple(output)


def load_species(path: Path) -> list[Species]:
    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError("species CSV provenance does not match the pinned revision")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != HEADERS:
            raise DataError("species CSV headers do not match the schema")
        output: list[Species] = []
        for row in reader:
            try:
                species_id = int(row["id"])
                gender_rate = int(row["gender_rate"])
                capture_rate = int(row["capture_rate"])
            except (TypeError, ValueError) as error:
                raise DataError("species CSV contains a non-numeric field") from error
            if species_id != len(output) + 1:
                raise DataError("species IDs must be continuous from 1 through 151")
            if not row["name"] or row["primary_type"] not in TYPES or row["primary_type"] == "None":
                raise DataError(f"species {species_id}: invalid identity or primary type")
            if row["secondary_type"] not in TYPES or not (0 <= gender_rate <= 8 or gender_rate == 255):
                raise DataError(f"species {species_id}: invalid type or gender rate")
            if not 1 <= capture_rate <= 255 or row["stage"] not in STAGES or row["acquisition"] not in ACQUISITIONS:
                raise DataError(f"species {species_id}: invalid capture, stage, or acquisition")
            output.append(
                Species(
                    species_id,
                    row["name"],
                    row["primary_type"],
                    row["secondary_type"],
                    gender_rate,
                    capture_rate,
                    row["stage"],
                    row["acquisition"],
                    parse_evolutions(row["evolutions"], species_id),
                )
            )
    if len(output) != 151:
        raise DataError(f"expected 151 species, found {len(output)}")
    return output


def generate(species: list[Species]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_v2_species.py. Do not edit.",
        f"// PokeAPI api-data revision: {REVISION}",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
    ]
    for row in species:
        lines.append(f"static const char NAME_{row.species_id:03d}[] = {json.dumps(row.name, ensure_ascii=False)};")
    lines.extend(("", "static const EvolutionRule EVOLUTION_RULES[] = {"))
    for row in species:
        for evolution in row.evolutions:
            lines.append(
                "    EvolutionRule{" +
                f"{evolution.target}, EvolutionTrigger::{evolution.trigger}, {evolution.level}, " +
                f"EvolutionItem::{evolution.item}" +
                "},"
            )
    lines.extend(("};", "", "static const SpeciesData KANTO_SPECIES[] = {"))
    offset = 0
    for row in species:
        lines.append(
            "    SpeciesData{" +
            f"{row.species_id}, NAME_{row.species_id:03d}, PokemonType::{row.primary_type}, " +
            f"PokemonType::{row.secondary_type}, {row.gender_rate}, {row.capture_rate}, " +
            f"EvolutionStage::{row.stage}, Acquisition::{row.acquisition}, {offset}, {len(row.evolutions)}" +
            "},"
        )
        offset += len(row.evolutions)
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(KANTO_SPECIES) / sizeof(KANTO_SPECIES[0]) == KANTO_SPECIES_COUNT);",
            "static_assert(sizeof(EVOLUTION_RULES) / sizeof(EVOLUTION_RULES[0]) < 256);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=root / "scripts/data/pokemon-kanto-v2.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_species(args.input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated species table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
