#!/usr/bin/env python3
"""Generate the flash-resident crop pack copied to SD after firmware updates."""

from pathlib import Path
import hashlib

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "assets_local" / "harvest" / "crops"
OUTPUT = ROOT / "src" / "apps_local" / "farm" / "FarmCropAssets.h"
NAMES = [f"stage-{stage}.bmp" for stage in range(1, 5)]


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16]) + ",")
    return "\n".join(rows)


digest = hashlib.sha256()
parts = [
    "#pragma once",
    "",
    "// Generated by tools_local/harvest/gen_crop_assets.py. Do not edit.",
    "#include <cstddef>",
    "#include <cstdint>",
    "",
    "namespace farm::assets {",
]

for index, name in enumerate(NAMES, start=1):
    data = (SOURCE / name).read_bytes()
    digest.update(name.encode("ascii"))
    digest.update(data)
    parts.extend(
        [
            f"inline constexpr uint8_t kStage{index}[] = {{",
            format_bytes(data),
            "};",
            "",
        ]
    )

version = digest.hexdigest()[:16]
parts.extend(
    [
        "struct CropAsset {",
        "  const char* name;",
        "  const uint8_t* data;",
        "  size_t size;",
        "};",
        "",
        f'inline constexpr char kVersion[] = "{version}";',
        "inline constexpr CropAsset kCropAssets[] = {",
    ]
)
for index, name in enumerate(NAMES, start=1):
    parts.append(f'    {{"{name}", kStage{index}, sizeof(kStage{index})}},')
parts.extend(["};", "", "}  // namespace farm::assets", ""])

OUTPUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
